#标题
site_name: Decred.club德信俱乐部 

#设置github开源地址
repo_url: https://github.com/decredclub/decredclub-zh
repo_name: 德信github源码

#主题设置
theme:
  custom_dir: overrides
  name: material
  logo: img/decred_logo_symbol_color_gradient_128.svg #设置logo
  favicon: img/decred_logo_symbol_color_gradient_128.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.tabs.link
    - navigation.instant
    - navigation.indexes
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 





#页脚设置
extra:
  social:
    - icon: octicons/mark-github-16
      link: https://github.com/decredclub/decredclub-zh
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/decredproject
      name: Twitter
    - icon: fontawesome/brands/medium
      link: https://medium.com/decred
      name: Medium
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/decred/
      name: Reddit
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/decredchannel
      name: YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/decredproject/
      name: LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/decredproject/
      name: Facebook
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/DecredProject
      name: Weibo


#插件设置
plugins:
  - search: #搜索
      lang: 
        - en
        - zh
  - social: #社交卡片设置
      cards_color:
        fill: "#0FF1CE"
        text: "#FFFFFF"
      cards_font: Ubuntu





nav: #导航菜单设置
 - 首页: 
   - 关于我们: index.md
 - 德信咨讯: 
   - 新闻资讯: index.md 
   - Dcr月报: index.md
   - 社区活动: index.md
   - Dcr行情讨论: news/price/dcr-usdt.md
 - DCR行情评论: 
   - DCR-USDT:  news/price/dcr-usdt.md
   - DCR-BTC:  news/price/dcr-btc.md
 - 应用中心:
   - 下载中心:  application-Center/application-Center.md
   - 使用教程:  application-Center/application-Center.md
 - Decred文档: 
   - Decred简介: Decred-Documentation/Introduction/Decred简介.md
   - 入门: 
     - 初学者指南: Decred-Documentation/Getting-Started/初学者指南.md
     - 项目历史: Decred-Documentation/Getting-Started/Decred的项目历史.md
     - 获取DCR: Decred-Documentation/Getting-Started/获取Decred.md
     - 使用区块浏览器: Decred-Documentation/Getting-Started/使用区块浏览器.md
     - 加入矩阵: Decred-Documentation/Getting-Started/加入Matrix上的Decred社区.md
     - 文章与媒体: Decred-Documentation/Getting-Started/文章与媒体.md
     - 业务介绍: Decred-Documentation/Getting-Started/业务介绍.md
   - 治理:
     - 治理概览: Decred-Documentation/Governance/治理概览.md
     - 治理平台Politeia: 
        - Politeia简介: Decred-Documentation/Governance/Politeia/Politeia简介.md
        - 编写提案指南: Decred-Documentation/Governance/Politeia/编写提案指南.md
        - 提案示例: Decred-Documentation/Governance/Politeia/提案示例.md
        - 审查制度: Decred-Documentation/Governance/Politeia/审查制度.md
     - 共识规则投票: 
        - 共识规则投票概述: Decred-Documentation/Governance/Consensus/共识规则投票概述.md
        - 如何投票: Decred-Documentation/Governance/Consensus/如何投票.md
        - 验证选票: Decred-Documentation/Governance/Consensus/验证选票.md
        - 共识投票存档: Decred-Documentation/Governance/Consensus/共识投票存档.md
     - Decred宪法: Decred-Documentation/Governance/Decred宪法.md

   - 钱包: 
     - Decrediton（图形用户界面）: 404.md
     - CLI 钱包: 404.md
     - 特殊目的公司: 404.md
     - 硬件钱包: 404.md
     - 手机钱包: 404.md
   - 权益证明投票:
     - PoS 投票概览: 404.md
     - 如何质押: 404.md
     - 兑换脚本: 404.md   
   - 工作证明挖矿: 404.md
   - 隐私: 
     - 一般隐私: 404.md
     - CoinShuffle++: 
        - CoinShuffle++ 概述: 404.md
        - 如何使用 CSPP: 404.md
   - 闪电网络:
     - 闪电网络概述: 404.md
     - 备份: 404.md
     - 瞭望塔: 404.md
     - dcrincli: 404.md
   - 常问问题: 
     - 一般常见问题解答: 404.md
     - 配置常见问题: 404.md
     - 钱包和种子常见问题解答: 404.md
     - 区块常见问题: 404.md
     - PoW 常见问题解答: 404.md
     - 常见错误和解决方案: 404.md
     - 权益证明: 404.md
   - 先进的: 
     - 手动 CLI 安装: 404.md
     - 时间: 404.md
     - 验证二进制文件: 404.md
     - 预挖: 404.md
     - 发行: 404.md
     - 删除你的钱包: 404.md
     - 导航 Politeia 数据: 404.md
     - 单人权益证明 (PoS) 投票: 404.md
     - 操作 VSP: 404.md
     - 运行全节点: 404.md
     - 安全: 404.md
     - 原子互换: 404.md
     - Decred 种子和 BIP-0039: 404.md
     - 安全冷钱包设置: 404.md
   - 研究: 
     - 研究概览: 404.md
     - 混合设计: 404.md
     - 去中心化权益池: 404.md
     - 椭圆曲线签名算法: 404.md
     - BLAKE-256 哈希函数: 404.md
     - 签名脚本隔离和欺诈证明: 404.md
     - 出块时间: 404.md
     - Schnorr 签名: 404.md
     - 杂项改进: 404.md
   - 贡献: 
     - 贡献概述: 404.md
     - 贡献者报酬: 404.md
   - 词汇表: 404.md
   - 关于: 
     - 执照: 404.md
